apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    pipeline.alpha.openshift.io/uses: '[{"name": "allprod-pipeline",  "kind": "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: pipeline-allprod
    name: allprod-pipeline
    template: pipeline-allprod
  name: allprod-pipeline
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: "pipeline {\n    agent none\n    stages {\n        stage ('moveNewToStable')
        {\n            steps {\n                script {\n                    openshift.withCluster()
        {\n                        openshift.withProject('fisdemoprod') {\n                            \n
        \                           openshift.tag(\"fisdemoprod/fisgateway-service-new:latest\",
        \"fisdemoprod/fisgateway-service-stable:latest\")\n                            \n
        \                           def deploymentConfig = openshift.selector(\"dc\",
        \"fisgateway-service-stable\")\n                            \n                            def
        rm = deploymentConfig.rollout()\n                            \n                            //Rollout
        latest deployment\n                            rm.latest()\n                            \n
        \                           //Check Rollout status - blocks and waits for
        rollout to complete\n                            rm.status()\n                        }\n
        \                   }\n                }\n            }\n        }\n        \n
        \       stage ('UpdateRouteToStable') {\n            steps {\n                script
        {\n                    def stableroute = [\n                        \"apiVersion\":
        \"v1\",\n                        \"kind\": \"Route\",\n                        \"metadata\":
        [\n                            \"labels\": [\n                                'component':
        'fisgateway-service-stable',\n                                'group': 'quickstarts',\n
        \                               'project': 'fisgateway-service-stable',\n
        \                               'provider': 's2i',\n                                'template':
        'fisgateway-service',\n                                'version': '1.0.0'\n
        \                           ],\n                            \"name\": \"fisgateway-service\",\n
        \                           \"namespace\": \"fisdemoprod\",\n                            \"annotations\"
        : [\n                                'haproxy.router.openshift.io/balance':
        'roundrobin'\n                                ],\n                            ],\n
        \                       \"spec\": [\n                            \"host\":
        \"fisgateway-service-fisdemoprod.apps.demolab.local\",\n                            \"to\":
        [\n                                \"kind\": \"Service\",\n                                \"name\":
        \"fisgateway-service-stable\",\n                            ],\n                        ]\n
        \                   ]\n                    openshift.withCluster() {\n                        openshift.withProject('fisdemoprod')
        {\n                                \n                            echo \"Deleting
        existing route\"\n                            \n                            openshift.selector(\"route\",
        \"fisgateway-service\").delete()\n                            \n                            echo
        \"Creating Route\"\n                            def objs = openshift.create(stableroute)\n
        \                               \n                            \n                        }
        \  \n                    }\n                }\n            }\n        }\n
        \       stage ('StopNewServices') {\n            steps {\n                script
        {\n                    openshift.withCluster() {\n                        openshift.withProject('fisdemoprod')
        {\n                            \n                            // stop the new
        deployment pods until next time!\n                            openshift.selector(\"dc\",
        \"fisgateway-service-new\").scale(\"--replicas=0\")\n                                \n
        \                           \n                        }   \n                    }\n
        \               }\n            }\n        } \n    }\n}\n\n/*node('maven')
        { \n  env.threescaleurl = \"https://fusedemo-admin.3scale.net\";\n  env.apiaccesstoken
        = \"143d1a90ea5d369a88ec35310f06b86fec8569a1c34c21eaffc9f9906947962a\";    \n
        \ env.appplanid = \"2357355899471\";\n  env.metricsid = \"2555418019263\";\n
        \ env.normallimit = 50;\n  \n  env.newnamespace = \"fisdemoprod\";\n  env.stablenamespace
        = \"fisdemoprod\";\n  \n  stage('moveNewToStable') { \n    print 'Move new
        image stream to stable image stream' \n    openshiftTag(namespace: \"${env.newnamespace}\",
        sourceStream: \"fisgateway-service\",  sourceTag: \"latest\", destinationnamespace:
        \"${env.stablenamespace}\", destinationStream: \"fisgateway-service-stable\",
        destinationTag: \"latest\")\n  }\n  \n  stage('UpdateRouteToStable') {\n    print
        'deleteroute' \n    openshiftDeleteResourceByKey keys: \"fisgateway-service\",
        namespace: \"${env.stablenamespace}\", types: \"route\", verbose: \"true\"\n
        \   \n    print 'Update Route to only point to stable service' \n    openshiftCreateResource
        jsonyaml: \"{    'apiVersion': 'v1',    'kind': 'Route',    'metadata': {
        \       'labels': {            'component': 'fisgateway-service-stable',            'group':
        'quickstarts',            'project': 'fisgateway-service-stable',            'provider':
        's2i',            'template': 'fisgateway-service',            'version':
        '1.0.0'        },        'name': 'fisgateway-service',        'namespace':
        '${env.stablenamespace}'    },    'spec': {        'host': 'fisgateway-service-${env.stablenamespace}.192.168.64.2.nip.io',
        \       'to': {            'kind': 'Service',            'name': 'fisgateway-service-stable',
        \           'weight': 100        },        'wildcardPolicy': 'None'    }}\",
        namespace: \"${env.stablenamespace}\", verbose: \"false\"\n  } \n  \n  stage('StopNewServices')
        {\n    print 'Stop all new service pod' \n    openshiftScale depCfg: \"fisgateway-service-new\",
        namespace: \"${env.newnamespace}\", replicaCount: \"0\", verifyReplicaCount:
        \"true\", verbose: \"true\"\n  }\n  \n  stage('GetCurrentLimitId') { \n    print
        'Get Current Limit Id'\n    env.LIMIT_ID = sh (\n      script: \"curl --silent
        -X GET \\\"${env.threescaleurl}/admin/api/application_plans/${env.appplanid}/metrics/${env.metricsid}/limits.xml?access_token=${env.apiaccesstoken}\\\"
        --stderr - | sed -e 's,.*<id>\\\\([^<]*\\\\)</id>.*,\\\\1,g' \", \n      returnStdout:
        true\n    ).trim()\n    echo env.LIMIT_ID\n  }\n  \n  stage('UpdateLimitToAllProd')
        { \n    print 'Update 3scale Limit back to normal'\n    sh  \"echo Updating
        Id ${env.LIMIT_ID} to less request ${env.normallimit} per min because of AB
        Testing\"\n    sh  \"curl -s -o /dev/null -w \\\"%{http_code}\\\\n\\\" -X
        PUT  \\\"${env.threescaleurl}/admin/api/application_plans/${env.appplanid}/metrics/${env.metricsid}/limits/${env.LIMIT_ID}.xml\\\"
        -d \\'access_token=${env.apiaccesstoken}&period=minute&value=${env.normallimit}\\'\"
        \ \n  }\n} */"
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
